### ISSUE TITLE
How i convert JSON to JSON-LD?

### ISSUE THREAD

**Issue by bakatest-me** [piprate/json-gold#19]
```json
{
 "@context": ["https://www.w3.org/2018/credentials/v1", "https://schema.org/"]
  "id": "http://example.edu/credentials/332",
  "type": ["VerifiableCredential", "IdentityCredential"],
  "issuer": "https://example.edu/issuers/4",
  "issued": "2017-02-24",
  "credentialSubject": {
    "name": "J. Doe",
    "address": {
      "streetAddress": "10 Rue de Chose",
      "postalCode": "98052",
      "addressLocality": "Paris",
      "addressCountry": "FR"
    },
    "birthDate": "1989-03-15"
}
```
jsonld.Unmarshall(byte,data)
data.SomeSchemaView
Thank you.

**Comment by xkortex** [comment]
See this answer: https://stackoverflow.com/questions/27564369/json-to-json-ld

If your fields already match a schema/ontology, just append the right context(s), and you are golden! However if it isn't an exact match, and I could be mistaken here, but you will likely need to write some sort of mapper, even if it's lightweight. 

E.g. you could use a regex which takes any of "id" "@id" "_id" "$id" and replaces with "@ld":
`([_@]?id)` -> `@id`. Otherwise code does not have any way of definitively knowing your "dumb json" field is a given type (that's basically the whole point of ontologies). How you do that mapping/inference is up to you. E.g. you could write a rule that if a field key is within a Levenschtein distance of an actual ontology field, convert that key to its "proper" name. You are getting into knowledge capture at this point, which can get as complicated as you let it.
