### ISSUE TITLE
proc.Normalize producing different results than jsonld.js

### ISSUE THREAD

**Issue by joeltg** [piprate/json-gold#23]
I _think_ that the canonicalization implementation sometimes assigns the wrong blank node labels.

The minimal example I can find is
```json
{
  "@context": {
    "@vocab": "http://schema.org/"
  },
  "http://www.w3.org/ns/prov#wasAttributedTo": {
    "name": "The Small Town Gazette"
  },
  "@graph": {
    "@id": "http://example.com/jane-doe",
    "jobTitle": "Professor"
  }
}
```
```golang
package main

import (
  "encoding/json"
  "fmt"
  "os"

  ld "github.com/piprate/json-gold/ld"
)

func main() {
  var d map[string]interface{}
  decoder := json.NewDecoder(os.Stdin)
  _ = decoder.Decode(&d)

  proc := ld.NewJsonLdProcessor()
  opts := ld.NewJsonLdOptions("")
  opts.Format = "application/n-quads"

  result, _ := proc.Normalize(d, opts)
  fmt.Print(result.(string))
}
```

```
% go build -o normalize
% ls
doc.json        main.go         normalize
% cat doc.json | ./normalize
<http://example.com/jane-doe> <http://schema.org/jobTitle> "Professor" _:c14n0 .
_:c14n0 <http://www.w3.org/ns/prov#wasAttributedTo> _:c14n1 .
_:c14n1 <http://schema.org/name> "The Small Town Gazette" .
% cat doc.json | jsonld normalize
<http://example.com/jane-doe> <http://schema.org/jobTitle> "Professor" _:c14n1 .
_:c14n0 <http://schema.org/name> "The Small Town Gazette" .
_:c14n1 <http://www.w3.org/ns/prov#wasAttributedTo> _:c14n0 .
```

... this is using the [jsonld-cli](https://github.com/digitalbazaar/jsonld-cli) tool. AFAICT, the second result is correct (the graph name should be `_:c14n1` and the blank node should be `_:c14n0`), but I may be wrong (in which case this is a problem with jsonld.js!).

**Comment by kazarena** [comment]
@joeltg,

The truth is that both answers are correct :-) Because the examples you gave use different normalisation algorithms. Your sample program is using the default option for JSON-goLD, **URGNA2012**, while the jsonld-cli uses **URDNA2015**. They have slightly different treatment of blank nodes.

If you use URDNA2015 in the example above, you will get the same answer. Please refer to either [README](https://github.com/piprate/json-gold#normalize) or the [example](https://github.com/piprate/json-gold/blob/master/examples/normalize.go). We will make URDNA2015 a default option soon, but for now you will need to define the target algorithm explicitly.

Stan

**Comment by joeltg** [comment]
Aaaa! I didn't even think that URGNA2012 might be the default. Sorry for taking your time; thanks so much for maintaining this.
